### PR TITLE
JavaScript review

### PR DESCRIPTION
**Pull request by coder543**

### CODE REVIEW

**Comment by coder543** [comment]
I assume the `function openTab` at the top came from somewhere else? If so, you should always leave a comment giving a link to the original source if it came from StackOverflow, or just credit to the author by name or username if you don't have any other info.

But, it's a very opaque function. `i` and `x` are useless variable names.

**Comment by samdotson1992** [comment]
It's from 3wschools.com

**Comment by samdotson1992** [comment]
And I intend to refactor that code

**Comment by coder543** [comment]
This inline script should probably be moved into `main.js`: https://github.com/samdotson1992/BrewMap/blob/master/index.html#L107

**Pull request merged**
